[package]
name = "chat-gpt-ideas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
guessing_game = { path = "./src/libs/guessing_game" }
temp_conv = { path = "./src/libs/temp_conv" }
